<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>WorktreeManager.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup Label="Dependencies">
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="../Library/Library.csproj" />
  </ItemGroup>

  <ItemGroup Label="Global Usings">
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
