<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Dependencies">
    <PackageVersion Include="CliWrap" Version="3.10.0" />
    <PackageVersion Include="CSharpier.MSBuild" Version="1.2.6" />
    <PackageVersion Include="MSTest" Version="4.0.1" />
  </ItemGroup>
</Project>
